title: Adam's Scribbles
description: >-
  Writing, code, and photos by Adam Jensen
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ehseejay.com"
twitter_username: acjensen
github_username: acj

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

